title: "LiDAR :: snow :: ice :: code"
email: pete@gadom.ski
description: >
  I do research, code development, and field work for CRREL.
baseurl: ""
url: "http://www.gadom.ski"
twitter_username: petegadomski
github_username:  gadomski
google_analytics: UA-90644232-1

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
