title: "LiDAR :: snow :: ice :: code"
email: pete@gadom.ski
description: >
  I do research, code development, field work, and other sundry for CRREL.
baseurl: ""
url: "http://www.gadom.ski"
twitter_username: pgadomski
github_username:  gadomski

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
