title: "@gadomski"
email: pete@gadom.ski
description: >
  dogs and charts, mostly
baseurl: ""
url: "http://www.gadom.ski"
twitter_username: petegadomski
github_username:  gadomski
google_analytics: UA-90644232-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
