base_url = "https://www.gadom.ski"
title = "gadom.ski"
description = "Geopsatial open-source"
default_language = "en"
taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]
theme = "abridge"

[markdown]

[extra]
author = "Pete Gadomski"
headhr = true
foothr = true
keywords = "geospatial, software, raster, point cloud, vector, open source, stac"
menu = [
    { url = "about", name = "About", slash = true, blank = false, size = "s110" },
    { url = "categories", name = "Categories", slash = true, blank = false, size = "s110" },
    { url = "tags", name = "Tags", slash = true, blank = false, size = "s110" },
    { url = "publications", name = "Publications", slash = true, blank = false, size = "s110" },
]
textlogo = '<font color="#f90">gadom</font>.ski'
sitedesc = true
copyright_override = "© 2017-$CURRENT_YEAR Pete Gadomski"
footer_credit = false
mail_encode = true
feeds = true
mail = "pete@gadom.ski"
github = "gadomski"
